routes/web.php
<?php

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */

/*
  |--------------------------------------------------------------------------
  | Helpers Routes
  |--------------------------------------------------------------------------
  |
 */


Route::group(['prefix' => '/backend'], function() {
    Route::post('ajax/upload', 'Helpers\AjaxController@anyUpload');
    Route::any('ajax/editorupload', 'Helpers\AjaxController@anyEditorupload');
    Route::any('ajax/removeimage', 'Helpers\AjaxController@anyRemoveimage');
    Route::any('ajax/browse', 'Helpers\AjaxController@anyBrowse');
});

Route::post('ajax/upload', 'Front\AjaxController@anyUpload');

/*
  |--------------------------------------------------------------------------
  | Test Routes
  |--------------------------------------------------------------------------
  |
 */
Route::get('git-pull', function() {
    $username = 'admin';
    $password = 'adm1n@';
    if (!isset($_SERVER['PHP_AUTH_USER'])) {
        $server_auth = isset($_SERVER['HTTP_AUTHORIZATION']) ?
                $_SERVER['HTTP_AUTHORIZATION'] :
                (isset($_SERVER['REDIRECT_HTTP_AUTHORIZATION']) ?
                $_SERVER['REDIRECT_HTTP_AUTHORIZATION'] : '');
        if ($server_auth)
            list($_SERVER['PHP_AUTH_USER'], $_SERVER['PHP_AUTH_PW']) = explode(':', base64_decode(substr(
                                    $server_auth, 6)));
    }

    if (( isset($_SERVER['PHP_AUTH_USER']) && ( $_SERVER['PHP_AUTH_USER'] == $username ) ) AND ( isset($_SERVER['PHP_AUTH_PW']) && ( $_SERVER['PHP_AUTH_PW'] == $password ))) {
        echo '<pre>';
        echo `git pull 2>&1` . "\r\n";
//        \Artisan::call('migrate', ["--force" => true]);
    } else {
        header('WWW-Authenticate: Basic realm="Unauthorized"');
        header('HTTP/1.0 401 Unauthorized');
        exit;
    }
});
Route::get('php.info', function() {
    echo phpinfo();
    die;
});

/*
  |--------------------------------------------------------------------------
  | Back End Routes
  |--------------------------------------------------------------------------
  |
 */
Route::get('/backend', function () {
    return \Redirect::to('./backend/auth/login')->send();
});


Route::group(['namespace' => 'Backend', 'middleware' => ['web', 'backendAuth', 'roles', 'backendActions'], 'prefix' => '/backend'], function() {
    //Authentication
    Route::any('auth/login', 'AuthController@anyLogin');
    Route::any('auth/logout', 'AuthController@anyLogout');
//    Route::any('auth/forgot-password', 'AuthController@anyForgotPassword');
//    Route::any('auth/change-password/{code}/{email}', 'AuthController@anyChangePassword');
//    Route::get('auth/lockedscreen', 'AuthController@anyLockedscreen');
    //Dashboard
    Route::get('dashboard', 'DashboardController@anyIndex');
    Route::get('cashfix', 'DashboardController@anyCashfix');
    /**
     * Home Page
     */
//    //Contact Us
//    Route::get('contact-us', 'ContactUsController@anyIndex');
//    Route::get('contact-us/export', 'ContactUsController@anyExport');
//    Route::any('contact-us/details/{id}', 'ContactUsController@anyDetails');
//    Route::get('contact-us/delete/{id}', 'ContactUsController@anyDelete');
    //Settings
//    Route::any('settings', 'SettingsController@anyIndex');
    //Languages
//    Route::any('languages', 'LanguagesController@anyIndex');
//    Route::any('languages/create', 'LanguagesController@anyCreate');
//    Route::any('languages/edit/{id}', 'LanguagesController@anyEdit');
//    Route::get('languages/delete/{id}', 'LanguagesController@getDelete');
//    Route::get('languages/restore/{id}', 'LanguagesController@getRestore');
//    Route::get('languages/delete-forever/{id}', 'LanguagesController@getDeleteForever');
//    Route::get('languages/defaulting/{id}', 'LanguagesController@getDefaulting');
//    Route::get('languages/activated/{id}', 'LanguagesController@getActivated');
//    Route::any('languages/files/{id}', 'LanguagesController@anyFiles');
//    Route::get('languages/choose-language/{id}', 'LanguagesController@getChooseLanguage');
    //Pages
    Route::get('pages', 'PagesController@anyIndex');
    Route::any('pages/create', 'PagesController@anyCreate');
    Route::any('pages/edit/{id}', 'PagesController@anyEdit');
    Route::any('pages/delete/{id}', 'PagesController@anyDelete');
    //Pages Actions
    Route::get('pages/page-actions/{id}', 'PagesController@anyPageActions');
    Route::any('pages/create-page-actions/{id}', 'PagesController@anyCreatePageActions');
    Route::any('pages/edit-page-actions/{id}/{page_id}', 'PagesController@anyEditPageActions');
    Route::get('pages/delete-page-actions/{id}', 'PagesController@anyDeletePageActions');
    Route::get('pages/pages-generate', 'PagesController@anyPagesGenerate');
    //Roles
    Route::get('roles', 'RolesController@anyIndex');
    Route::any('roles/create', 'RolesController@anyCreate');
    Route::any('roles/edit/{id}', 'RolesController@anyEdit');
    Route::any('roles/delete/{id}', 'RolesController@anyDelete');
    Route::any('roles/role-actions/{id}', 'RolesController@anyRoleActions');
    //Backend Users
    Route::get('backend-users', 'BackendUsersController@anyIndex');
    Route::any('backend-users/profile', 'BackendUsersController@anyProfile');
    Route::any('backend-users/create', 'BackendUsersController@anyCreate');
    Route::any('backend-users/edit/{id}', 'BackendUsersController@anyEdit');
    Route::get('backend-users/delete/{id}', 'BackendUsersController@anyDelete');
    Route::get('backend-users/activated/{id}', 'BackendUsersController@anyActivated');
    //Production Lines
//    Route::get('lines', 'LinesController@anyIndex');
//    Route::any('lines/create', 'LinesController@anyCreate');
//    Route::any('lines/edit/{id}', 'LinesController@anyEdit');
//    Route::get('lines/delete/{id}', 'LinesController@anyDelete');
    //kpisvalues
    Route::any('kpisvalues', ['as' => 'backend.kpisvalues', 'uses' => 'KpisValuesController@anyIndex']);
    Route::any('kpisvalues/create', 'KpisValuesController@anyCreate');
    Route::any('kpisvalues/edit/{line_id}/{date}', 'KpisValuesController@anyEdit');
    Route::get('kpisvalues/delete/{line_id}/{date}', 'KpisValuesController@anyDelete');


    Route::get('charts', 'ChartsController@anyIndex');
    Route::any('bigshow', 'BigshowController@anyBigshow');

//    //Cpanel
//    Route::any('cpanel', 'CpanelController@anyIndex');
//    Route::any('cpanel/create-cpanel', 'CpanelController@anyCreateCpanel');
//    Route::any('cpanel/edit-cpanel/{id}', 'CpanelController@anyEditCpanel');
//    Route::any('cpanel/delete-cpanel/{id}', 'CpanelController@anyDeleteCpanel');
//    Route::any('cpanel/emails', 'CpanelController@anyEmails');
//    Route::any('cpanel/create-email', 'CpanelController@anyCreateEmail');
//    Route::any('cpanel/change-password-email/{email}/{cpanel_id}', 'CpanelController@anyChangePasswordEmail');
//    Route::any('cpanel/edit-qouta/{email}/{cpanel_id}', 'CpanelController@anyEditQouta');
//    Route::any('cpanel/delete-email/{email}/{cpanel_id}', 'CpanelController@anyDeleteEmail');
});

/*
  |--------------------------------------------------------------------------
  | Front End Routes
  |--------------------------------------------------------------------------
  |
 */

Route::group(['namespace' => 'Front'], function() {
    $skip = ['backend'];
    if (!in_array(\Request::segment(1), $skip)) {
        return \Redirect::to('./backend')->send();
    }
});
//
//Route::group(['namespace' => 'Front', 'prefix' => '{language_symbol}', 'middleware' => ['web', 'languages', 'baseActions', 'minifyHtml']], function() {
//    Route::any('/404', 'PageNotFoundController@anyIndex');
//    Route::any('/', 'HomeController@anyIndex');
//});

app/Models/BackendUsers.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class BackendUsers extends BaseModel
{

    protected $table = 'backend_users';
    public $timestamps = true;
    public $ignored_unique = [
        'email',
        'phone',
    ];
    public $rules = [
        'name' => 'required',
        'email' => "required|E-Mail|Between:3,64|unique:backend_users,email",
        'phone' => "required|numeric|unique:backend_users,phone",
        'password' => 'min:5|required',
        'c_password' => 'same:password'
//        'image' => 'required'
    ];
    protected $guarded = ['id'];

    function language()
    {
        return $this->belongsTo('\App\Models\Languages', 'language_id');
    }

    function role()
    {
        return $this->belongsTo('\App\Models\Roles', 'role_id');
    }

    function getImageProfileAttribute()
    {
        if($this->image != '')
            return url('uploads/backend_users/' . $this->image);
        else
            return url('assets/images/avatar_user.png');
    }

}

app/Http/Controllers/Backend/BackendUsersController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Models\BackendUsers;
use App\Models\Languages;
use App\Models\Roles;

class BackendUsersController extends BackendController
{

    public function anyIndex(Request $request)
    {
        $data['users'] = BackendUsers::where('backend_users.id', '!=', session('backendUser')->id);
        if(session('rule')->is_super == true)
            $data['users'] = $data['users']->join('roles', 'roles.id', 'backend_users.role_id')->where('roles.is_super', false)->select('backend_users.*');
        $data['users'] = $data['users']->paginate(50);

        return view('backend.backend_options.backend_users.index', $data);
    }

    public function anyCreate(Request $request)
    {
        $data['languages'] = Languages::orderBy('sort', 'ASC')->get();
        $data['roles'] = Roles::orderBy('id', 'ASC');
        if(session('rule')->is_super == true)
            $data['roles'] = $data['roles']->get();
        else
            $data['roles'] = $data['roles']->where('is_super', false)->get();
        if($request->has('save'))
        {
            $request->request->remove('save');
            $user = new BackendUsers;
            if($user->validate($request->all()))
            {
                $request->request->remove('c_password');
                $request->merge(['password' => md5($request->password)]);
                if(isset($request->image) && $request->image != '')
                {
                    rename('./uploads/temp/' . $request->image, './uploads/backend_users/' . $request->image);
                }
                $code_generator = \App\Http\Controllers\Helpers\Functions::genrateRegistartionCode();
                $request->request->add(['is_active' => 1, 'code_generator' => $code_generator]);
                $user->fill($request->all());
                $user->save();
                session()->flash('success', 'Insert successfully');
                return redirect(\URL::Current());
            }
            else
            {
                foreach($user->errors() as $error)
                {
                    $validate[] = $error;
                }
                $data['validate_errors'] = $validate;
            }
        }

        return view('backend.backend_options.backend_users.create', $data);
    }

    public function anyEdit(Request $request, $id)
    {
        $data['languages'] = Languages::orderBy('sort', 'ASC')->get();
        $data['user'] = $user = BackendUsers::find($id);
        if(!is_object($user))
            return \App::abort(404);
        $data['roles'] = Roles::orderBy('id', 'ASC');
        if(session('rule')->is_super == true)
            $data['roles'] = $data['roles']->get();
        else
            $data['roles'] = $data['roles']->where('is_super', false)->get();
        if($request->has('save'))
        {
            if($request->has('password') && $request->password != '')
                $request->merge(['password' => md5($request->password), 'c_password' => md5($request->c_password)]);
            else
                $request->request->add(['password' => $user->password, 'c_password' => $user->password]);
            if($user->validate($request->all()))
            {
                $request->request->remove('save');
                $request->request->remove('c_password');

                if($request->image && empty($request->image))
                    rename('./uploads/temp/' . $request->image, './uploads/backend_users/' . $request->image);
                else
                {
                    if($request->image && file_exists('./uploads/temp/' . $request->image))
                        rename('./uploads/temp/' . $request->image, './uploads/backend_users/' . $request->image);
                }
                $user->fill($request->all());
                $user->save();
                session()->flash('success', 'Update successfully');
                return redirect(\URL::Current());
            }
            else
            {
                foreach($user->errors() as $error)
                {
                    $validate[] = $error;
                }
                $data['validate_errors'] = $validate;
            }
        }

        return view('backend.backend_options.backend_users.edit', $data);
    }

    public function anyDelete($id)
    {
        $object = BackendUsers::find($id);
        if(is_object($object))
        {
            $object->delete();
            $response = new \stdClass();
            $response->status = 'Ok';
            $response->message = 'Deleted successfully';
        }
        else
        {
            $response = new \stdClass();
            $response->status = 'Warning';
            $response->message = 'Row can not be deleted';
        }
        echo json_encode($response);
    }

    public function anyActivated($id)
    {
        $user = BackendUsers::find($id);
        if($user->is_active == 0)
            $user->is_active = 1;
        else
            $user->is_active = 0;

        $user->save();
    }

    public function anyProfile(Request $request)
    {
        $data['user'] = $user = BackendUsers::find(session('backendUser')->id);

        if($request->has('save'))
        {
            if($request->has('password') && $request->password != '')
                $request->merge(['password' => md5($request->password), 'c_password' => md5($request->c_password)]);
            else
                $request->request->add(['password' => $user->password, 'c_password' => $user->password]);
            if($user->validate($request->all()))
            {
                $request->request->remove('save');
                $request->request->remove('c_password');

                if($request->image && empty($request->image))
                    rename('./uploads/temp/' . $_POST['image'], './uploads/backend_users/' . $request->image);
                else
                {
                    if($request->image && file_exists('./uploads/temp/' . $request->image))
                        rename('./uploads/temp/' . $request->image, './uploads/backend_users/' . $request->image);
                }
                $user->fill($request->all());
                $user->save();
                session()->flash('success', 'Update successfully');
                return redirect(\URL::Current());
            }
            else
            {
                foreach($user->errors() as $error)
                {
                    $validate[] = $error;
                }
                $data['validate_errors'] = $validate;
            }
        }

        return view('backend.backend_options.backend_users.profile', $data);
    }

}

resources/views/backend/backend_options/backend_users/_form.blade.php
<?php

use App\Http\Controllers\Helpers\Html\Components;
use App\Http\Controllers\Helpers\Functions;

if (!isset($user))
    $user = new \App\Models\BackendUsers;
?>
<form method="post" class="form-horizontal" id="form">

    <div class="form-group">
        <div class="col-sm-6">
            <label class="control-label">Name</label>
            <input type="text" name="name" placeholder="Please Enter Name" class="form-control" value="{{Functions::issetPost('name', $user->name)}}" required >
        </div>
        <div class="col-sm-6">
            <label class="control-label">Email</label>
            <input type="email" name="email" placeholder="Please Enter Your Email" class="form-control" value="{{Functions::issetPost('email', $user->email)}}" required>
        </div>
    </div>

    <div class="form-group">
        <div class="col-sm-6">
            <label class="control-label">Phone</label>
            <input type="tel" name="phone" placeholder="Please Enter Phone" class="form-control" value="{{Functions::issetPost('phone', $user->phone)}}" required >
        </div>
        <div class="col-sm-6">
            <label class="control-label">Choose Roles</label>
            <select name="role_id" class="select2clear form-control" required>
                <option selected disabled>Please Choose</option>
                @foreach($roles as $role)
                <option {{Functions::selectedPost('role_id', $user->role_id, $role->id)}} value="{{$role->id}}">{{$role->name}}</option>
                @endforeach
            </select>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-6">
            <label class="control-label">Password</label>
            <input type="password" name="password" placeholder="Please Enter Password" class="form-control">
        </div>
        <div class="col-sm-6">
            <label class="control-label">Confirm Password</label>
            <input type="password" name="c_password" placeholder="Please Enter Same Password" class="form-control">
        </div>
    </div>

    <div class="form-group">
        <div class="col-sm-12">
            <div class="btn btn-default btn-file">
                <input type='hidden' name='image' value='{{$user->image}}' />
                <?php
                if ($user->image != '')
                    $user->image = './uploads/backend_users/' . $user->image;
                else
                    $user->image = './assets/images/avatar_user.png';
                ?>
                {!!Components::uploader($user->image)!!}
            </div>
            <p class="help-block">Upload Image Only , Max Size Image 2 MB</p>
        </div>
    </div>
    <div class="hr-line-dashed"></div>
    <div class="form-group">
        <input type="submit" name="save" class="btn btn-outline btn-primary" value="Save Changes" />
    </div>
</form>
<script>
    $(document).ready(function () {

        $("#form").validate({
            rules: {
                name: {
                    required: true,
                    minlength: 3
                },
                password: {
                    required: <?php
                if ($user->id > 0) {
                    echo 'false';
                } else {
                    echo 'true';
                }
                ?>,
                    minlength: 5
                },
                c_password: {
                    minlength: 5,
                    equalTo: '[name="password"]'
                },
                email: {
                    required: true,
                    email: true,
                    minlength: 10
                },
                phone: {
                    required: true,
                    number: true
                },
                role_id: {
                    required: true,
                    number: true
                }
            }
        });
    });
</script>

resources/views/backend/backend_options/backend_users/create.blade.php
@extends('backend.layout')
@section('title','Create | Backend Users Data')
@section('content')
@include('backend.message')

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-sm-4">
        <h2>Create Backend User Data</h2>
        <ol class="breadcrumb">
            <li>
                <a href="{{url('backend/dashboard')}}">Dashboard</a>
            </li>
            <li data-action='backendusers.index'>
                <a href="{{url('backend/backend-users')}}">Backend Users</a>
            </li>
            <li class="active">
                <strong>Create</strong>
            </li>
        </ol>
    </div>

</div>    

<div class="fh-breadcrumb animated fadeInRight">

    <div class="full-height">
        <div class="full-height-scroll border-left">

            <div class="element-detail-box">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="ibox float-e-margins">
                            <div class="ibox-title">
                                <h5></h5>
                                <div class="ibox-tools">

                                </div>
                            </div>
                            <div class="ibox-content">

                                @include('backend.backend_options.backend_users._form')  

                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>



</div>

@stop()

resources/views/backend/backend_options/backend_users/edit.blade.php
@extends('backend.layout')
@section('title','Update | Backend Users Data')
@section('content')
@include('backend.message')
<?php

use App\Http\Middleware\Roles; ?>
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-sm-4">
        <h2>Update Backend User Data</h2>
        <ol class="breadcrumb">
            <li>
                <a href="{{url('backend/dashboard')}}">Dashboard</a>
            </li>
            <li data-action='backendusers.index'>
                <a href="{{url('backend/backend-users')}}">Backend Users</a>
            </li>
            <li class="active">
                <strong>Update</strong>
            </li>
        </ol>
    </div>

</div>    

<div class="fh-breadcrumb animated fadeInRight">

    <div class="full-height">
        <div class="full-height-scroll border-left">

            <div class="element-detail-box">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="ibox float-e-margins">
                            <div class="ibox-title">
                                <h5></h5>
                                <div class="ibox-tools">

                                </div>
                            </div>
                            <div class="ibox-content">

                                @include('backend.backend_options.backend_users._form')  

                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>



</div>

@stop()

resources/views/backend/backend_options/backend_users/index.blade.php
@extends('backend.layout')
@section('title','Backend Users Data')
@section('content')
@include('backend.message')
<?php

use App\Http\Controllers\Helpers\Html\Themes;
use App\Http\Controllers\Helpers\Functions;
?>

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-sm-4">
        <h2>Backend Users Data </h2>
        <ol class="breadcrumb">
            <li>
                <a href="{{url('backend/dashboard')}}">Dashboard</a>
            </li>
            <li class="active">
                <strong>Backend Users</strong>
            </li>
        </ol>
    </div>
    <div class="col-sm-8" data-action="backendusers.create">
        <div class="title-action">
            <a href="{{url('backend/backend-users/create')}}" class="btn btn-outline btn-primary" id="stepCreate">Create New User</a>
        </div>
    </div>
</div>
<div class="fh-breadcrumb animated fadeInRight">

    <div class="full-height">
        <div class="full-height-scroll border-left">

            <div class="element-detail-box">


                <div class="row">
                    <div class="col-lg-12">
                        <div class="ibox float-e-margins">
                            <div class="ibox-title">
                                <h5></h5>
                                <div class="ibox-tools">
                                </div>
                            </div>
                            <div class="ibox-content">
                                <div class="table-responsive">
                                    <table class="table table-striped table-bordered table-hover example2" id="stepTable">
                                        <thead>
                                            <tr>
                                                <th>Name</th>
                                                <th>Image</th>
                                                <th>Settings</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach($users as $user)
                                            <tr>
                                                <td>{{$user->name}}</td>
                                                <td>{!!Themes::imageFancy($user->name, $user->image_profile)!!}</td>
                                                <td>
                                                    <a href="{{url(\URL::Current().'/edit/'.$user->id)}}" class=" btn btn-xs btn-outline btn-primary" data-action="backendusers.edit" id="stepEdit"><i class="fa fa-paste"></i> Update</a>
                                                    <button type="button" class="btn btn-xs btn-outline btn-warning" data-toggle="modal" data-target="#myModal{{$user->id}}" id="stepPreview"><i class="fa fa-twitch"></i> Preview</button>
                                                    <div class="modal inmodal" id="myModal{{$user->id}}" tabindex="-1" role="dialog" aria-hidden="true">
                                                        <div class="modal-dialog">
                                                            <div class="modal-content animated bounceInRight">
                                                                <div class="modal-header">
                                                                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                                                                    <i class="fa fa-laptop modal-icon"></i>
                                                                    <h4 class="modal-title">Preview All Data</h4>
                                                                </div>
                                                                <div class="modal-body">
                                                                    <blockquote>
                                                                        <p>
                                                                            <strong style="font-size: 18px;">Name</strong> : {{$user->name}}
                                                                        </p>

                                                                        <p>
                                                                            <strong style="font-size: 18px;">Email</strong> : {{$user->email}}
                                                                        </p>

                                                                        <p>
                                                                            <strong style="font-size: 18px;">Phone</strong> : {{$user->phone}}
                                                                        </p>

                                                                        <p>
                                                                            <strong style="font-size: 18px;">Role</strong> : @if(!empty($user->role->name)) {{$user->role->name}} @endif
                                                                        </p>

                                                                        <p>
                                                                            <strong style="font-size: 18px;">Creation Date</strong> : {{$user->createdAt()}}
                                                                        </p>

                                                                        <p>
                                                                            <strong style="font-size: 18px;">Update Date</strong> : {{$user->updatedAt()}}
                                                                        </p>
                                                                    </blockquote>
                                                                </div>
                                                                <div class="modal-footer">
                                                                    <button type="button" class="btn btn-white" data-dismiss="modal">Close</button>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    {!!Themes::deleteRow($user->id, url(\URL::Current().'/delete'),['data-action'=>"backendusers.delete"])!!}
                                                    {!!Themes::checkboxInput($user->is_active, $user->id, url(\URL::Current().'/activated'),  Functions::checked($user->is_active, true),['data-action'=>"backendusers.activated"])!!}
                                                </td>
                                            </tr>
                                            @endforeach
                                        </tbody>
                                    </table>
                                    {{$users->render()}}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>
    </div>



</div>



@stop()